# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JFrog.Conan
PackageVersion: 2.12.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Conan Package Manager_is1
ReleaseDate: 2025-01-27
AppsAndFeaturesEntries:
- ProductCode: Conan Package Manager_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '{code:DefDirRoot}\Conan'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.12.0/conan-2.12.0-windows-i686-installer.exe
  InstallerSha256: 4AD41844D79D875A1423C95214BA064843AE6E69840A9ACD24373C2A7682C1DC
- Architecture: x64
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.12.0/conan-2.12.0-windows-x86_64-installer.exe
  InstallerSha256: B8720A8679A92F93D90D16F16B8F285D56016AE95D3E7B52B31F76614E8CAE7D
ManifestType: installer
ManifestVersion: 1.9.0
