# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JFrog.Conan
PackageVersion: 2.16.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: /ALLUSERS
UpgradeBehavior: install
ProductCode: Conan Package Manager_is1
ReleaseDate: 2025-04-29
AppsAndFeaturesEntries:
- ProductCode: Conan Package Manager_is1
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '{code:DefDirRoot}\Conan'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.16.0/conan-2.16.0-windows-i686-installer.exe
  InstallerSha256: 79E1D8B8C8244EF63C1858DAE0448F9CA37A67A7DA5591337FF792B6394583DE
- Architecture: x64
  InstallerUrl: https://github.com/conan-io/conan/releases/download/2.16.0/conan-2.16.0-windows-x86_64-installer.exe
  InstallerSha256: 7A2623AFEFE11F9BD0552773BF4B26A27D1E5407A6BD89AD29B4C333A82D1DF4
ManifestType: installer
ManifestVersion: 1.9.0
